export const STORECONST = {
    GET_STORE: 'GET_STORE',
    GET_SINGLE_STORE: 'GET_SINGLE_STORE',
    ADD_STORE: 'ADD_STORE',
    UPDATE_STORE: 'UPDATE_STORE',
    DELETE_STORE: 'DELETE_STORE'
}

export const USERCONST = {
    GET_USER: 'GET_USER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT'
}